        const $ = id => document.getElementById(id);
        const P = { page: 'dash', ldm: false, sbC: false, fS: 1, img: null, imgU: null, title: '', price: '', desc: '', tags: [], theme: 'classic', fr: false, bcCh: { whatsapp: true, facebook: true, instagram: true, x: true } };

        /* Data persistence */
        function gD() { try { return JSON.parse(localStorage.getItem('kua_d') || '{}') } catch (e) { return {} } }
        function sD(d) { localStorage.setItem('kua_d', JSON.stringify(d)) }
        function getProfile() { return gD().profile || { name: '', businessName: '', brandName: '', ctaText: 'Order on WhatsApp', channels: { whatsapp: { connected: false, phone: '' }, instagram: { connected: false, username: '' }, twitter: { connected: false, username: '' }, linkedin: { connected: false, username: '' } } } }
        function saveProfile() { const d = gD(); d.profile = getProfile(); sD(d) }
        function getActivity() { return gD().activity || [] }
        function addActivity(item) { const d = gD(); d.activity = d.activity || []; d.activity.unshift(item); if (d.activity.length > 50) d.activity.length = 50; d.flyers = (d.flyers || 0) + (item.type === 'flyer' ? 1 : 0); d.broadcasts = (d.broadcasts || 0) + (item.type === 'broadcast' ? 1 : 0); sD(d) }

        const cM = { whatsapp: { n: 'WhatsApp', i: 'fa-brands fa-whatsapp', c: '#25D366' }, instagram: { n: 'Instagram', i: 'fa-brands fa-instagram', c: '#E4405F' }, twitter: { n: 'X (Twitter)', i: 'fa-brands fa-x-twitter', c: '#E7E9EA' }, linkedin: { n: 'LinkedIn', i: 'fa-brands fa-linkedin-in', c: '#0A66C2' } };
        const aTags = ['Premium Quality', 'Fast Delivery', 'Limited Stock', 'Best Seller', 'Free Shipping', 'New Arrival', 'Handmade', 'Organic'];

        /* Toast */
        function toast(m, t = 'info') { const c = $('ts'), cs = { success: 'border-green-500/40 bg-green-500/10 text-green-300', error: 'border-red-500/40 bg-red-500/10 text-red-300', warning: 'border-amber-500/40 bg-amber-500/10 text-amber-300', info: 'border-blue-400/40 bg-blue-400/10 text-blue-300' }, is = { success: 'fa-circle-check', error: 'fa-circle-xmark', warning: 'fa-triangle-exclamation', info: 'fa-circle-info' }, el = document.createElement('div'); el.className = `pointer-events-auto flex items-center gap-2 px-3.5 py-2.5 rounded-xl border backdrop-blur-xl text-[13px] font-medium ti ${cs[t]}`; el.innerHTML = `<i class="fa-solid ${is[t]}"></i><span>${m}</span>`; c.appendChild(el); setTimeout(() => { el.classList.remove('ti'); el.classList.add('to'); setTimeout(() => el.remove(), 300) }, 3000) }

        /* Nav */
        const pT = { dash: 'Dashboard', flyer: 'Flyer Generator', bcast: 'Broadcast Center', acct: 'Connected Accounts', set: 'Settings' };
        function nv(p) { P.page = p; $('pt').textContent = pT[p] || 'Kua'; document.querySelectorAll('.vw').forEach(v => v.classList.remove('on')); const t = $('v-' + p); if (t) t.classList.add('on'); document.querySelectorAll('.ni').forEach(b => { const a = b.dataset.n === p; b.classList.toggle('text-white', a); b.classList.toggle('bg-el', a); b.classList.toggle('text-nv-400', !a); b.classList.toggle('hover:bg-nv-800', !a); b.classList.toggle('hover:text-white', !a); }); document.querySelectorAll('.bn').forEach(b => { const a = b.dataset.bn === p; b.classList.toggle('text-el', a); b.classList.toggle('text-nv-600', !a) }); $('cnt').scrollTop = 0; if (p === 'acct') rAcct(); if (p === 'bcast') rBCP(); if (p === 'dash') rDash(); if (p === 'set') loadSet() }
        function tSB() { P.sbC = !P.sbC; $('sidebar').classList.toggle('col', P.sbC); $('main').style.marginLeft = window.innerWidth >= 768 ? (P.sbC ? '64px' : '256px') : '0' }
        function tLDM() { P.ldm = !P.ldm; document.querySelectorAll('.tog').forEach(t => t.classList.toggle('on', P.ldm)); document.body.classList.toggle('ldm', P.ldm); $('ldm-mt').textContent = P.ldm ? 'On' : 'Off'; if (P.fr && P.fS === 3) { $('fpw').classList.toggle('hidden', P.ldm); $('fpl').classList.toggle('hidden', !P.ldm) } toast(P.ldm ? 'Low Data Mode on' : 'Low Data Mode off', 'info') }

        /* Upload */
        function hFile(e) { const f = e.target.files[0]; if (f) pF(f) } function hDrop(e) { e.preventDefault(); e.currentTarget.classList.remove('dv'); const f = e.dataTransfer.files[0]; if (f) pF(f) }
        function pF(f) { if (!['image/jpeg', 'image/png', 'image/webp'].includes(f.type)) { toast('Use JPG, PNG, or WebP', 'error'); return } if (f.size > 10 * 1024 * 1024) { toast('Max 10MB', 'error'); return } const r = new FileReader(); r.onload = e => { const u = e.target.result, img = new Image(); img.onload = () => { P.img = img; P.imgU = u; $('up-h').classList.add('hidden'); $('up-v').classList.remove('hidden'); $('pv-i').src = u; $('pv-f').textContent = f.name; $('b1').disabled = false; toast('Image uploaded', 'success') }; img.src = u }; r.readAsDataURL(f) }
        function rmI() { P.img = null; P.imgU = null; $('up-h').classList.remove('hidden'); $('up-v').classList.add('hidden'); $('fi').value = ''; $('b1').disabled = true }

        /* Steps */
        function gS(n) {
            P.fS = n; document.querySelectorAll('.fs').forEach(s => s.classList.add('hidden')); $('f' + n).classList.remove('hidden'); for (let i = 1; i <= 4; i++) { const d = $('s' + i); d.className = 'sd'; if (i < n) { d.classList.add('dn'); d.innerHTML = '<i class="fa-solid fa-check text-[10px]"></i>' } else if (i === n) { d.classList.add('ac'); d.textContent = i } else { d.classList.add('pn'); d.textContent = i } if (i < 4) { const l = $('l' + i); l.className = 'sln mx-2 mt-[-14px]'; l.classList.add(i < n ? 'dn' : 'pn') } }
            if (n === 4) { $('bc-ti').textContent = P.title; $('bc-pr').textContent = '$' + P.price; $('bc-de').textContent = P.desc || ''; $('bc-th').src = P.imgU || ''; rBcC(); $('bc-rs').classList.add('hidden'); $('bc-er').classList.add('hidden'); $('bc-bn').disabled = false; $('bc-bn').innerHTML = '<i class="fa-solid fa-paper-plane mr-1.5"></i>Broadcast Now' }
            if (n === 3 && P.ldm) { $('fpw').classList.add('hidden'); $('fpl').classList.remove('hidden') } else if (n === 3) { $('fpw').classList.remove('hidden'); $('fpl').classList.add('hidden') }
        }

        /* Tags & Theme */
        function iTags() { $('tg-b').innerHTML = aTags.map(t => `<button type="button" onclick="tTg(this,'${t}')" class="tgb px-2 py-1 text-[11px] font-medium rounded-full border border-nv-700 text-nv-400 hover:border-el/30 hover:text-el transition-colors">${t}</button>`).join('') }
        function tTg(b, t) { const i = P.tags.indexOf(t); if (i > -1) { P.tags.splice(i, 1); b.classList.remove('border-el/50', 'text-el', 'bg-el/8'); b.classList.add('border-nv-700', 'text-nv-400') } else { P.tags.push(t); b.classList.add('border-el/50', 'text-el', 'bg-el/8'); b.classList.remove('border-nv-700', 'text-nv-400') } }
        function pTh(el) { document.querySelectorAll('.tc').forEach(c => c.classList.remove('sl')); el.classList.add('sl'); P.theme = el.dataset.t }

        /* Flyer Engine */
        const TH = { classic: { bg: '#FFFFFF', hBg: '#0F172A', hAc: '#3B82F6', tC: '#0F172A', dC: '#64748B', pBg: '#EFF6FF', pBd: '#BFDBFE', pC: '#3B82F6', cBg: '#25D366', cC: '#FFF', tgC: '#94A3B8', wC: '#CBD5E1', la: 'center', hBar: true, sh: true, gl: false, grdH: false, grdC: false, grdP: false }, midnight: { bg: '#0F172A', hBg: 'transparent', hAc: '#F59E0B', tC: '#FFF', dC: '#94A3B8', pBg: 'transparent', pBd: 'rgba(245,158,11,.2)', pC: '#F59E0B', cBg: 'transparent', cC: '#FFF', tgC: '#64748B', wC: '#475569', la: 'left', hBar: false, sh: false, gl: true, grdH: false, grdC: false, grdP: false }, neon: { bg: '#0F172A', hBg: 'gradient', hAc: '#FFF', tC: '#FFF', dC: '#94A3B8', pBg: 'gradient', pBd: 'transparent', pC: '#FFF', cBg: 'gradient', cC: '#FFF', tgC: '#64748B', wC: '#475569', la: 'center', hBar: true, sh: false, gl: true, grdH: true, grdC: true, grdP: true } };
        function rR(c, x, y, w, h, r) { r = Math.max(0, Math.min(r, Math.min(w, h) / 2)); c.beginPath(); c.moveTo(x + r, y); c.lineTo(x + w - r, y); c.quadraticCurveTo(x + w, y, x + w, y + r); c.lineTo(x + w, y + h - r); c.quadraticCurveTo(x + w, y + h, x + w - r, y + h); c.lineTo(x + r, y + h); c.quadraticCurveTo(x, y + h, x, y + h - r); c.lineTo(x, y + r); c.quadraticCurveTo(x, y, x + r, y); c.closePath() }
        function iC(c, img, dx, dy, dw, dh) { const ir = img.width / img.height, ar = dw / dh; let sx, sy, sw, sh; if (ir > ar) { sh = img.height; sw = Math.max(1, sh * ar); sx = (img.width - sw) / 2; sy = 0 } else { sw = img.width; sh = Math.max(1, sw / ar); sx = 0; sy = (img.height - sh) / 2 } c.drawImage(img, sx, sy, sw, sh, dx, dy, dw, dh) }
        function trT(c, t, mw) { if (c.measureText(t).width <= mw) return t; let s = t; while (s.length > 0 && c.measureText(s + '...').width > mw) s = s.slice(0, -1); return s + '...' }
        function wrT(c, t, mw, lh, ml) { const ws = t.split(' '); let ls = [], cur = ''; for (const w of ws) { const test = cur ? cur + ' ' + w : w; if (c.measureText(test).width > mw && cur) { ls.push(cur); cur = w; if (ls.length >= ml) break } else cur = test } if (cur && ls.length < ml) ls.push(cur); return ls }

        function rFlyer(cv, d, tk) {
            const t = TH[tk], c = cv.getContext('2d'), W = 1080, H = 1080; cv.width = W; cv.height = H; const pr = getProfile(), br = pr.brandName || pr.businessName || 'Kua', ct = pr.ctaText || 'Order on WhatsApp', cx = W / 2, lx = 80, ta = t.la === 'left' ? 'left' : 'center';
            c.fillStyle = t.bg; c.fillRect(0, 0, W, H);
            if (tk === 'midnight') { const g = c.createRadialGradient(W * .3, H * .1, 0, W * .3, H * .1, W * .8); g.addColorStop(0, 'rgba(59,130,246,.04)'); g.addColorStop(1, 'transparent'); c.fillStyle = g; c.fillRect(0, 0, W, H) }
            if (t.hBar) { if (t.grdH) { const g = c.createLinearGradient(0, 0, W, 0); g.addColorStop(0, '#3B82F6'); g.addColorStop(1, '#8B5CF6'); c.fillStyle = g; c.fillRect(0, 0, W, 88) } else { c.fillStyle = t.hBg; c.fillRect(0, 0, W, 88); if (tk === 'classic') { c.fillStyle = t.hAc; c.fillRect(0, 0, 6, 88) } } c.fillStyle = '#FFF'; c.font = 'bold 34px Inter,system-ui,sans-serif'; c.textAlign = ta; c.textBaseline = 'middle'; const bx = ta === 'left' ? lx : cx; c.fillText(br, bx, 44); if (tk === 'classic') { const bw = c.measureText(br).width; c.fillStyle = t.hAc; c.font = '600 13px Inter,system-ui,sans-serif'; c.fillText('SOCIAL MARKETING', bx + bw + 14, 44) } if (!t.grdH) { c.fillStyle = t.hAc; c.fillRect(0, 88, W, 3) } } else { c.fillStyle = '#FFF'; c.font = 'bold 30px Inter,system-ui,sans-serif'; c.textAlign = 'left'; c.textBaseline = 'top'; c.fillStyle = t.hAc; c.fillRect(lx - 16, 22, 8, 8); c.fillStyle = '#FFF'; c.fillText(br, lx, 18); c.fillStyle = t.hAc; c.fillRect(lx, 54, 56, 3) }
            if (t.gl) { const ix = ta === 'left' ? lx : 60, iw = ta === 'left' ? 920 : 960, iy = t.hBar ? 116 : 80, ih = 460; const gc = c.createRadialGradient(ix + iw / 2, iy + ih / 2, 0, ix + iw / 2, iy + ih / 2, iw * .5); gc.addColorStop(0, 'rgba(59,130,246,.06)'); gc.addColorStop(1, 'transparent'); c.fillStyle = gc; c.fillRect(ix - 100, iy - 50, iw + 200, ih + 100) }
            const imgX = ta === 'left' ? lx : 60, imgW = ta === 'left' ? 920 : 960, imgY = t.hBar ? 116 : 80, imgH = 460;
            c.save(); rR(c, imgX, imgY, imgW, imgH, 18); if (t.sh) { c.shadowColor = 'rgba(0,0,0,.06)'; c.shadowBlur = 28; c.shadowOffsetY = 8; c.fillStyle = '#F1F5F9'; c.fill(); c.shadowColor = 'transparent'; c.shadowBlur = 0; c.shadowOffsetY = 0 } c.clip(); if (d.image) iC(c, d.image, imgX, imgY, imgW, imgH); else { c.fillStyle = '#E2E8F0'; c.fillRect(imgX, imgY, imgW, imgH) } c.restore();
            if (tk === 'neon') { rR(c, imgX, imgY, imgW, imgH, 18); c.strokeStyle = 'rgba(59,130,246,.3)'; c.lineWidth = 2; c.stroke() }
            let cy = imgY + imgH + 32; c.fillStyle = t.tC; c.font = 'bold 40px Inter,system-ui,sans-serif'; c.textAlign = ta; c.textBaseline = 'top'; const mxW = ta === 'left' ? 820 : 940; c.fillText(trT(c, d.title, mxW), ta === 'left' ? lx : cx, cy);
            if (d.desc) { cy += 50; c.fillStyle = t.dC; c.font = '400 19px Inter,system-ui,sans-serif'; const ls = wrT(c, d.desc, mxW, 26, 2); ls.forEach((l, i) => c.fillText(l, ta === 'left' ? lx : cx, cy + i * 26)); cy += ls.length * 26 }
            cy += 16; const pStr = '$' + d.price; c.font = 'bold 44px Inter,system-ui,sans-serif'; const pw = c.measureText(pStr).width; const plW = pw + 48, plH = 58, plR = 29, plX = (ta === 'left' ? lx : cx) - (ta === 'left' ? 0 : plW / 2);
            if (t.grdP) { const g = c.createLinearGradient(plX, cy, plX + plW, cy); g.addColorStop(0, '#3B82F6'); g.addColorStop(1, '#06B6D4'); rR(c, plX, cy, plW, plH, plR); c.fillStyle = g; c.fill() } else { rR(c, plX, cy, plW, plH, plR); c.fillStyle = t.pBg; c.fill(); if (t.pBd !== 'transparent') { rR(c, plX, cy, plW, plH, plR); c.strokeStyle = t.pBd; c.lineWidth = 1.5; c.stroke() } }
            c.fillStyle = t.pC; c.textAlign = 'center'; c.textBaseline = 'middle'; c.fillText(pStr, plX + plW / 2, cy + plH / 2); cy += 72;
            if (tk === 'classic') { c.setLineDash([6, 6]); c.strokeStyle = '#E2E8F0'; c.lineWidth = 1.5; c.beginPath(); c.moveTo(ta === 'left' ? lx : 100, cy); c.lineTo(ta === 'left' ? lx + 400 : W - 100, cy); c.stroke(); c.setLineDash([]) } else if (tk === 'midnight') { c.strokeStyle = 'rgba(245,158,11,.2)'; c.lineWidth = 1.5; c.beginPath(); c.moveTo(lx, cy); c.lineTo(lx + 180, cy); c.stroke() } else { c.fillStyle = 'rgba(148,163,184,.3)';[cx - 16, cx, cx + 16].forEach(dx => { c.beginPath(); c.arc(dx, cy, 2.5, 0, Math.PI * 2); c.fill() }) }
            cy += 28; const ctW = ta === 'left' ? 340 : 380, ctH = 56, ctR = 28, ctX = (ta === 'left' ? lx : cx) - (ta === 'left' ? 0 : ctW / 2);
            c.save(); if (t.grdC) { const g = c.createLinearGradient(ctX, cy, ctX + ctW, cy); g.addColorStop(0, '#3B82F6'); g.addColorStop(1, '#06B6D4'); c.fillStyle = g; c.shadowColor = 'rgba(59,130,246,.3)'; c.shadowBlur = 18; c.shadowOffsetY = 4; rR(c, ctX, cy, ctW, ctH, ctR); c.fillStyle = g; c.fill() } else if (tk === 'midnight') { rR(c, ctX, cy, ctW, ctH, ctR); c.strokeStyle = '#FFF'; c.lineWidth = 1.5; c.stroke() } else { c.fillStyle = t.cBg; c.shadowColor = 'rgba(37,211,102,.3)'; c.shadowBlur = 18; c.shadowOffsetY = 4; rR(c, ctX, cy, ctW, ctH, ctR); c.fillStyle = t.cBg; c.fill() } c.restore();
            c.fillStyle = t.cC; c.font = 'bold 21px Inter,system-ui,sans-serif'; c.textAlign = 'center'; c.textBaseline = 'middle'; c.fillText(ct, ctX + ctW / 2, cy + ctH / 2 + 1); cy += ctH + 28;
            const tags = d.tags.length ? d.tags : ['Premium Quality', 'Fast Delivery']; c.font = '500 14px Inter,system-ui,sans-serif'; c.fillStyle = t.tgC; c.textAlign = ta; c.fillText(trT(c, tags.slice(0, 3).map(x => '\u2022 ' + x).join('     '), mxW), ta === 'left' ? lx : cx, cy);
            c.fillStyle = t.wC; c.font = '500 12px Inter,system-ui,sans-serif'; c.textAlign = 'center'; c.textBaseline = 'bottom'; c.fillText('powered by Kua', cx, H - 20); c.textAlign = 'left'; c.textBaseline = 'alphabetic'
        }

        function genF() {
            const ti = $('i-t').value.trim(), pr = $('i-p').value.trim(), de = $('i-d').value.trim(); if (!ti) { $('s2e').classList.remove('hidden'); $('s2et').textContent = 'Product title is required.'; return } if (!pr || isNaN(parseFloat(pr))) { $('s2e').classList.remove('hidden'); $('s2et').textContent = 'Enter a valid price.'; return } $('s2e').classList.add('hidden'); P.title = ti; P.price = pr; P.desc = de; $('gov').classList.remove('hidden');
            setTimeout(() => { rFlyer($('fc'), { image: P.img, title: P.title, price: P.price, desc: P.desc, tags: P.tags }, P.theme); rFlyer($('pv-c'), { image: P.img, title: P.title, price: P.price, desc: P.desc, tags: P.tags }, P.theme); $('gov').classList.add('hidden'); P.fr = true; addActivity({ type: 'flyer', title: ti, price: pr, time: Date.now(), theme: P.theme }); gS(3); toast('Flyer generated', 'success') }, 900)
        }
        function dlF() { const c = $('fc'), a = document.createElement('a'); a.download = `kua-${P.title.replace(/\s/g, '-').toLowerCase()}-${Date.now()}.png`; a.href = c.toDataURL('image/png'); document.body.appendChild(a); a.click(); a.remove(); toast('Downloaded', 'success') }
        function shF() { const c = $('fc'); c.toBlob(b => { if (!b) return; const f = new File([b], 'kua-flyer.png', { type: 'image/png' }); if (navigator.share && navigator.canShare && navigator.canShare({ files: [f] })) { navigator.share({ title: 'Kua Flyer', files: [f] }).catch(() => { }) } else if (navigator.clipboard && window.ClipboardItem) { navigator.clipboard.write([new ClipboardItem({ 'image/png': b })]).then(() => toast('Copied', 'success')).catch(() => toast('Use Download', 'warning')) } else toast('Not supported', 'warning') }, 'image/png') }

        function startOver() { rmI(); $('i-t').value=''; $('i-p').value=''; $('i-d').value=''; $('tc').textContent='0'; $('dc').textContent='0'; P.title=''; P.price=''; P.desc=''; gS(1); }

        /* Broadcast Cards */
        function rBcC() {
            const pr = getProfile(); const box = $('bc-cs'); box.innerHTML = ''; const waC = !!pr.channels?.whatsapp?.connected, igC = !!pr.channels?.instagram?.connected, twC = !!pr.channels?.twitter?.connected;
            [{ k: 'whatsapp', c: waC }, { k: 'facebook', c: igC }, { k: 'instagram', c: igC }, { k: 'x', c: twC }].forEach(({ k, c: co }) => { const m = { whatsapp: { n: 'WhatsApp', i: 'fa-brands fa-whatsapp', c: '#25D366' }, facebook: { n: 'Facebook', i: 'fa-brands fa-facebook-f', c: '#1877F2' }, instagram: { n: 'Instagram', i: 'fa-brands fa-instagram', c: '#E4405F' }, x: { n: 'X (Twitter)', i: 'fa-brands fa-x-twitter', c: '#E7E9EA' } }[k]; const sl = P.bcCh[k]; const el = document.createElement('div'); el.className = `cc ${sl ? 'sl' : ''} bg-nv-800/50 border border-nv-700/30 rounded-xl p-3 flex items-center gap-3 ${!co ? 'opacity-40' : ''}`; el.innerHTML = `<div class="w-9 h-9 rounded-lg flex items-center justify-center shrink-0" style="background:${m.c}12"><i class="${m.i}" style="color:${m.c}"></i></div><div class="flex-1 min-w-0"><div class="text-[13px] font-bold text-white">${m.n}</div><div class="text-[10px] text-nv-500">${co ? 'Connected' : 'Not linked'}</div></div><div class="w-5 h-5 rounded-full ${sl ? 'bg-el border-el' : 'border-nv-600'} border-2 flex items-center justify-center shrink-0">${sl ? '<i class="fa-solid fa-check text-[8px] text-white"></i>' : ''}</div>`; el.onclick = () => { P.bcCh[k] = !P.bcCh[k]; rBcC() }; box.appendChild(el) })
        }

        /* Broadcast Execution */
        async function doBC() {
            const pr = getProfile(), sel = Object.entries(P.bcCh).filter(([_, v]) => v).map(([k]) => k); if (!sel.length) { $('bc-er').classList.remove('hidden'); return } $('bc-er').classList.add('hidden'); const btn = $('bc-bn'); btn.disabled = true; btn.innerHTML = '<span class="spn mr-1.5"></span>Sending...'; const res = $('bc-rs'), list = $('bc-ls'); res.classList.remove('hidden'); list.innerHTML = ''; const ph = pr.channels?.whatsapp?.phone || '', msg = `${P.title}\n$${P.price}\n${P.desc || ''}`;
            const nM = { whatsapp: 'WhatsApp', facebook: 'Facebook', instagram: 'Instagram', x: 'X (Twitter)' }, iM = { whatsapp: 'fa-brands fa-whatsapp', facebook: 'fa-brands fa-facebook-f', instagram: 'fa-brands fa-instagram', x: 'fa-brands fa-x-twitter' }, cM2 = { whatsapp: '#25D366', facebook: '#1877F2', instagram: '#E4405F', x: '#E7E9EA' };
            const items = {}; sel.forEach(ch => { const d = document.createElement('div'); d.className = 'flex items-center gap-2.5 bg-nv-800/40 rounded-lg p-2.5'; d.innerHTML = `<div class="w-7 h-7 rounded-lg flex items-center justify-center shrink-0" style="background:${cM2[ch]}15"><i class="${iM[ch]} text-xs" style="color:${cM2[ch]}"></i></div><div class="flex-1 min-w-0"><div class="flex items-center justify-between mb-1"><span class="text-[11px] font-bold text-white">${nM[ch]}</span><span class="cs text-[10px] font-semibold text-nv-500">Preparing...</span></div><div class="w-full h-1 bg-nv-700 rounded-full overflow-hidden"><div class="pb h-full rounded-full transition-all duration-300" style="width:0%;background:${cM2[ch]}"></div></div></div>`; list.appendChild(d); items[ch] = { st: d.querySelector('.cs'), br: d.querySelector('.pb') } });
            for (let i = 0; i < sel.length; i++) {
                const ch = sel[i], it = items[ch]; await new Promise(r => setTimeout(r, 300 + i * 200)); it.st.textContent = 'Sending...'; it.st.className = 'cs text-[10px] font-semibold text-amb'; it.br.style.width = '50%'; await new Promise(r => setTimeout(r, 400)); it.br.style.width = '85%';
                let ok = true; try { if (ch === 'whatsapp') { try { $('fc').toBlob(b => { if (b) navigator.clipboard.write([new ClipboardItem({ 'image/png': b })]) }) } catch(err){} window.open(`https://wa.me/?text=${encodeURIComponent(msg + '\n\n*(Paste flyer image here!)*')}`, '_blank'); } else if (ch === 'x') window.open(`https://twitter.com/intent/tweet?text=${encodeURIComponent(msg)}`, '_blank'); else if (ch === 'facebook') window.open(`https://www.facebook.com/sharer/sharer.php?quote=${encodeURIComponent(msg)}`, '_blank'); else if (ch === 'instagram') { ok = false; it.st.textContent = 'Open Instagram'; it.st.className = 'cs text-[10px] font-semibold text-amb'; it.br.style.width = '100%'; it.br.style.background = '#F59E0B'; continue } } catch (e) { ok = false }
                await new Promise(r => setTimeout(r, 400)); it.br.style.width = '100%'; if (ok) { it.st.textContent = 'Opened'; it.st.className = 'cs text-[10px] font-semibold text-green-400' } else { it.st.textContent = 'Failed'; it.st.className = 'cs text-[10px] font-semibold text-cor'; it.br.style.background = '#EF4444' }
            }
            addActivity({ type: 'broadcast', title: P.title, channels: sel, time: Date.now() }); btn.disabled = false; btn.innerHTML = '<i class="fa-solid fa-rotate-right mr-1.5"></i>Send Again'; toast('Broadcast initiated', 'success')
        }

        /* Connected Accounts */
        function rAcct() {
            const pr = getProfile(); const box = $('ac-cs'); box.innerHTML = ''; const chs = [{ k: 'whatsapp', n: 'WhatsApp', i: 'fa-brands fa-whatsapp', c: '#25D366', d: 'Enable WhatsApp to pick contacts or groups and broadcast freely.', t: 'toggle' }, { k: 'instagram', n: 'Instagram', i: 'fa-brands fa-instagram', c: '#E4405F', d: 'Connect Instagram for feed posts and stories.', t: 'oauth', u: 'https://www.instagram.com/accounts/login/' }, { k: 'twitter', n: 'X (Twitter)', i: 'fa-brands fa-x-twitter', c: '#E7E9EA', d: 'Link X to post tweets with your flyers.', t: 'oauth', u: 'https://twitter.com/i/flow/login' }, { k: 'linkedin', n: 'LinkedIn', i: 'fa-brands fa-linkedin-in', c: '#0A66C2', d: 'Connect LinkedIn for professional network sharing.', t: 'oauth', u: 'https://www.linkedin.com/login' }];
            chs.forEach(ch => {
                const co = pr.channels?.[ch.k]?.connected, dt = pr.channels?.[ch.k] || {}; const el = document.createElement('div'); el.className = 'bg-nv-800/50 border border-nv-700/30 rounded-xl p-5 transition-all hover:border-nv-600/40';
                el.innerHTML = `<div class="flex items-start gap-3.5"><div class="w-11 h-11 rounded-xl flex items-center justify-center shrink-0" style="background:${ch.c}12"><i class="${ch.i} text-lg" style="color:${ch.c}"></i></div><div class="flex-1 min-w-0"><div class="flex items-center gap-2 mb-0.5"><h3 class="text-sm font-bold text-white">${ch.n}</h3>${co ? '<span class="text-[10px] font-semibold text-green-400 bg-green-400/10 px-2 py-0.5 rounded-full">Connected</span>' : '<span class="text-[10px] font-semibold text-nv-500 bg-nv-700/30 px-2 py-0.5 rounded-full">Not linked</span>'}</div><p class="text-xs text-nv-400 leading-relaxed mb-3">${ch.d}</p>${co && ch.t === 'oauth' ? `<p class="text-xs text-nv-300 mb-3"><i class="fa-solid fa-at text-[10px] mr-1"></i>${dt.username || 'Authorized'}</p>` : ''}
<div class="flex items-center gap-2">${co ? `<button onclick="ulkCh('${ch.k}')" class="px-3 py-2 bg-cor/10 hover:bg-cor/15 text-cor text-xs font-semibold rounded-lg transition-colors border border-cor/15"><i class="fa-solid fa-link-slash mr-1"></i>Disconnect</button>` : ch.t === 'toggle' ? `<button onclick="cfOA('${ch.k}')" class="px-3 py-2 bg-el hover:bg-el-d text-white text-xs font-semibold rounded-lg transition-colors"><i class="fa-solid fa-check mr-1"></i>Enable</button>` : `<button onclick="lkOA('${ch.k}','${ch.u}')" class="px-3 py-2 bg-el hover:bg-el-d text-white text-xs font-semibold rounded-lg transition-colors"><i class="fa-solid fa-link mr-1"></i>Connect ${ch.n}</button>`}</div></div></div>`; box.appendChild(el)
            })
        }

        function lkPh(k) { const v = $('ph-' + k).value.trim(); if (!v || v.length < 7) { toast('Enter a valid phone number', 'error'); return } const pr = getProfile(); pr.channels[k] = { connected: true, phone: v }; saveProfile(); rAcct(); rDash(); addActivity({ type: 'connect', channel: k, time: Date.now() }); toast('WhatsApp number linked', 'success') }
        function lkOA(k, url) { window.open(url, '_blank', 'width=600,height=700'); toast(`Opening ${cM[k].n} — click "I've Connected" when done`, 'info'); setTimeout(() => { const cards = $('ac-cs').children; for (const cd of cards) { const btn = cd.querySelector(`[onclick*="lkOA('${k}'"]`); if (btn) { btn.outerHTML = `<div class="flex items-center gap-2"><button onclick="cfOA('${k}')" class="px-3 py-2 bg-green-500/15 hover:bg-green-500/20 text-green-400 text-xs font-semibold rounded-lg transition-colors border border-green-500/20"><i class="fa-solid fa-check mr-1"></i>I've Connected</button><button onclick="rAcct()" class="px-2.5 py-2 text-nv-500 text-xs font-semibold rounded-lg hover:text-nv-300 transition-colors">Cancel</button></div>`; break } } }, 700) }
        function cfOA(k) { const pr = getProfile(); const fake = k === 'instagram' ? '@' + (pr.businessName || 'mybusiness').replace(/\s/g, '').toLowerCase() : k === 'twitter' ? '@' + (pr.businessName || 'mybusiness').replace(/\s/g, '').toLowerCase() : (pr.businessName || 'mybusiness').replace(/\s/g, '').toLowerCase(); pr.channels[k] = { connected: true, username: fake }; saveProfile(); rAcct(); rDash(); addActivity({ type: 'connect', channel: k, time: Date.now() }); toast(`${cM[k].n} connected`, 'success') }
        function ulkCh(k) { const pr = getProfile(); pr.channels[k] = { connected: false, phone: '', username: '' }; saveProfile(); rAcct(); rDash(); addActivity({ type: 'disconnect', channel: k, time: Date.now() }); toast(`${cM[k].n} disconnected`, 'info') }

        /* Dashboard */
        function rDash() {
            const pr = getProfile(), d = gD(); $('dash-w').textContent = 'Welcome to Kua'; const nName = pr.name || pr.businessName || 'Kua User'; $('sb-nm').textContent = nName; $('sb-av').textContent = nName.charAt(0).toUpperCase(); $('st-fl').textContent = d.flyers || 0; $('st-bc').textContent = d.broadcasts || 0;
            const conns = Object.values(pr.channels || {}).filter(c => c?.connected).length; $('d-ch-c').textContent = conns; $('d-ch-l').textContent = conns ? conns + ' linked' : 'None linked';
            const box = $('d-chs'); box.innerHTML = '';['whatsapp', 'instagram', 'twitter', 'linkedin'].forEach(k => { const m = cM[k], co = !!pr.channels?.[k]?.connected; box.innerHTML += `<div class="bg-nv-800/40 border border-nv-700/25 rounded-xl p-3 flex flex-col items-center text-center"><div class="w-8 h-8 rounded-full flex items-center justify-center mb-1" style="background:${m.c}12"><i class="${m.i} text-sm" style="color:${m.c}"></i></div><div class="text-[10px] font-bold text-white">${m.n}</div><div class="text-[9px] ${co ? 'text-green-400' : 'text-nv-500'} mt-0.5">${co ? '<i class="fa-solid fa-circle text-[4px] mr-0.5"></i>Linked' : 'Not linked'}</div></div>` });
            const act = getActivity(); const aEl = $('dash-activity');
            if (!act.length) { aEl.innerHTML = '<div class="px-5 py-6 text-center text-xs text-nv-500">No activity yet. Create your first flyer to get started.</div>' } else {
                aEl.innerHTML = act.slice(0, 8).map(a => {
                    const ago = timeAgo(a.time); let icon = '', color = '', label = '';
                    if (a.type === 'flyer') { icon = 'fa-solid fa-wand-magic-sparkles'; color = 'text-el'; label = `Created flyer: ${a.title}` }
                    else if (a.type === 'broadcast') { icon = 'fa-solid fa-tower-broadcast'; color = 'text-wa'; label = `Broadcast "${a.title}" to ${a.channels?.length || 0} channels` }
                    else if (a.type === 'connect') { icon = 'fa-solid fa-link'; color = 'text-green-400'; label = `Connected ${cM[a.channel]?.n || a.channel}` }
                    else if (a.type === 'disconnect') { icon = 'fa-solid fa-link-slash'; color = 'text-cor'; label = `Disconnected ${cM[a.channel]?.n || a.channel}` }
                    return `<div class="px-5 py-2.5 flex items-center gap-3 hover:bg-nv-700/10 transition-colors"><div class="w-7 h-7 rounded-lg bg-nv-700/30 flex items-center justify-center shrink-0"><i class="${icon} text-[10px] ${color}"></i></div><div class="flex-1 min-w-0"><p class="text-xs text-nv-300 truncate">${label}</p></div><span class="text-[10px] text-nv-600 shrink-0">${ago}</span></div>`
                }).join('')
            }
        }

        function timeAgo(ts) { const s = Math.floor((Date.now() - ts) / 1000); if (s < 60) return 'just now'; if (s < 3600) return Math.floor(s / 60) + 'm ago'; if (s < 86400) return Math.floor(s / 3600) + 'h ago'; if (s < 604800) return Math.floor(s / 86400) + 'd ago'; return Math.floor(s / 604800) + 'w ago' }

        /* Broadcast Page */
        function rBCP() {
            const pr = getProfile(); const box = $('bc-ov'); box.innerHTML = '';['whatsapp', 'instagram', 'twitter', 'linkedin'].forEach(k => { const m = cM[k], co = !!pr.channels?.[k]?.connected; box.innerHTML += `<div class="bg-nv-800/40 border border-nv-700/25 rounded-xl p-3 flex flex-col items-center text-center"><div class="w-8 h-8 rounded-full flex items-center justify-center mb-1" style="background:${m.c}12"><i class="${m.i} text-sm" style="color:${m.c}"></i></div><div class="text-[10px] font-bold text-white">${m.n}</div><div class="text-[9px] ${co ? 'text-green-400' : 'text-nv-500'} mt-0.5">${co ? 'Connected' : 'Not linked'}</div></div>` });
            const act = getActivity().filter(a => a.type === 'broadcast'); const hEl = $('bc-hi');
            if (!act.length) { hEl.innerHTML = '<div class="px-5 py-6 text-center text-xs text-nv-500">No broadcasts yet.</div>' } else { hEl.innerHTML = act.slice(0, 6).map(a => `<div class="px-5 py-2.5 flex items-center gap-3"><div class="w-8 h-8 rounded-lg bg-nv-700/30 flex items-center justify-center shrink-0"><i class="fa-solid fa-image text-nv-500 text-[10px]"></i></div><div class="flex-1 min-w-0"><div class="text-xs font-semibold text-white truncate">${a.title || 'Flyer'}</div><div class="text-[10px] text-nv-500 mt-0.5">${a.channels?.length || 0} channels</div></div><span class="text-[10px] text-nv-500 shrink-0">${timeAgo(a.time)}</span><span class="text-[10px] font-semibold text-green-400 bg-green-400/10 px-2 py-0.5 rounded-full shrink-0">Sent</span></div>`).join('') }
        }

        /* Settings */
        function loadSet() { const pr = getProfile(); $('s-nm').value = pr.name || ''; $('s-bz').value = pr.businessName || ''; $('s-br').value = pr.brandName || ''; $('s-ct').value = pr.ctaText || '' }
        function saveSet() { const pr = getProfile(); pr.name = $('s-nm').value.trim() || pr.name; pr.businessName = $('s-bz').value.trim() || pr.businessName; pr.brandName = $('s-br').value.trim() || pr.businessName; pr.ctaText = $('s-ct').value.trim() || pr.ctaText; saveProfile(); rDash(); toast('Saved', 'success') }
        function resetAll() { localStorage.removeItem('kua_d'); location.reload() }

        /* Init */
        function init() { iTags(); rDash(); nv('dash'); $('main').style.marginLeft = window.innerWidth >= 768 ? (P.sbC ? '64px' : '256px') : '0' }
        window.addEventListener('resize', () => { $('main').style.marginLeft = window.innerWidth >= 768 ? (P.sbC ? '64px' : '256px') : '0' });
        document.addEventListener('keydown', e => { if (e.target.classList.contains('tog') && (e.key === 'Enter' || e.key === ' ')) { e.preventDefault(); e.target.click() } });
        init();
